version: "3.3"

services:

  client:
    container_name: client
    networks:
      - hostnet
    image: client
    build: client
    command: "python3 -u /container/service.py"
    volumes:
      - ./client:/container
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime:ro

    environment:
      - DISPLAY
    devices:
      - /dev/video0
      - /dev/nvhost-as-gpu
      - /dev/nvhost-ctrl
      - /dev/nvhost-ctrl-gpu
      - /dev/nvhost-ctxsw-gpu
      - /dev/nvhost-dbg-gpu
      - /dev/nvhost-gpu
      - /dev/nvhost-prof-gpu
      - /dev/nvhost-sched-gpu
      - /dev/nvhost-tsg-gpu
      - /dev/nvmap
      - /dev/snd

networks:

  hostnet:
    driver: bridge