version: "3.3"

services:

  bridge:
    container_name: bridge
    networks:
      - hostnet
    build:
      context: bridge
    ports:
      - "1883:1883"
    command: "mosquitto -c /container/mosquitto_broker_cloud.conf"
    volumes:
      - ./bridge:/container

  server:
    container_name: server
    networks:
      - hostnet
    volumes:
      - ./server:/container
    build:
      context: server
    command: "python3 -u /container/service.py"
    volumes:
      - ./server:/container

networks:

  hostnet:
    driver: bridge